#!/bin/bash

cd .. && cd ./feed_engine_auth      && git checkout master  &&  git pull origin master
cd .. && cd ./feed_engine_front_end && git checkout master  &&  git pull origin master
cd .. && cd ./feed_engine_api       && git checkout master  &&  git pull origin master
cd .. && cd ./costner_goes_postal   && git checkout master  &&  git pull origin master
cd .. && cd ./foofoberry            && git checkout master  &&  git pull origin master
