auth:     sh -c 'cd ./feed_engine_auth && rails s -p 3000'
frontend: sh -c 'cd ./feed_engine_front_end && rails s -p 3002'
api:      sh -c 'cd ./feed_engine_api && rails s -p 3001'
proxy:    sh -c 'cd ./feed_engine_proxy && rackup config.ru -p 9292'
costner:  sh -c 'cd ./costner_goes_postal && rackup config.ru -p 9293'
